# Generated by Django 5.0.6 on 2024-06-01 17:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_message_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='mail_time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='mailing',
            name='next_send_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='сообщение'),
        ),
    ]
