# Generated by Django 5.0.6 on 2024-06-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_rename_mail_time_mailing_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='next_send_time',
            field=models.DateTimeField(),
        ),
    ]
